Feature/WS-22300/update-list-companies
helloworld1812/paychex-ruby-gem pull request #7
Opened 2023-07-12 17:03 UTC by prashant-shrikant

1) Lookup company by displayId to avoid timeout issue. 
2) Update minor version

2023-07-13 06:05 UTC, mayankdedhia reviewed
@prashant-shrikant do we know how this change affects the response when we fetch a company for whom there is no access or fetch a non-existing company, are both cases giving the same response?

2023-07-13 08:15 UTC, suyogbaldota-harbinger requested changes
Apart from handling for non existing paychex companies or no access to fetch the company as Mayank asked, everything looks good.

2023-07-14 03:10 UTC, prashant-shrikant commented
> @prashant-shrikant do we know how this change affects the response when we fetch a company for whom there is no access or fetch a non-existing company, are both cases giving the same response?

@mayankdedhia Yes those scenarios have been tested and in both cases give the same response. 

I will of course test this thoroughly by importing the gem into `workstream-backend` as well.

2023-07-17 05:14 UTC, mayankdedhia approved these changes

2023-07-17 07:21 UTC, suyogbaldota-harbinger approved these changes

2023-07-18 20:52 UTC, merged